<Project>
  <ItemGroup>
    <PackageVersion Include="BepInEx.Core" Version="5.4.21" />
    <PackageVersion Include="BepInEx.PluginInfoProps" Version="2.1.0" />
    <PackageVersion Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" />
    <PackageVersion Include="HarmonyX" Version="2.9.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>
